---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: k8s-debugger-policy
  namespace: fluxv2-tutorial-deployment
spec:
  imageRepositoryRef:
    name: k8s-debugger-imagerepo
  policy:
    semver:
      range: '>=1.x.x'

