---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: k8s-debugger-policy
  namespace: fluxv2-tutorial-deployment
spec:
  imageRepositoryRef:
    name: k8s-debugger-imagerepo
  filterTags:
    pattern: ^[1-9]{1}\.[0-9]{1}\.[0-9]{1}-[0-9]{12}-[a-f0-9]{7}$
  policy:
    semver:
      range: '>=1.x.x'