---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mamdouni-ghcr-helm-source
  namespace: fluxv2-tutorial-deployment-helm
spec:
  interval: 1m0s
  secretRef:
    name: ghcr-mamdouni-charts-auth
  type: oci
  url: oci://ghcr.io/mamdouni/charts

