apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxv2-tutorial-deployment-kustomization
  namespace: fluxv2-tutorial-deployment
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxv2-tutorial-deployment-source
    namespace: fluxv2-tutorial-deployment
  targetNamespace: fluxv2-tutorial-deployment