apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxv2-tutorial-deployment
  namespace: fluxv2-tutorial-deployment
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: fluxv2-tutorial-deployment
    namespace: fluxv2-tutorial-deployment
  path: ./
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: fluxv2-tutorial-deployment