---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: google-chat-provider
  namespace: default
spec:
  channel: Test Flux CD
  secretRef:
    name: google-chat-webhook-secret
  type: googlechat
  username: FluxBot

