---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: test-flux-cd-google-bot-alert
  namespace: default
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRepository
    name: '*'
  providerRef:
    name: google-chat-provider

